# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bounce' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bounce
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Alamofire', '4.4.0'
end
